import type { Tool } from "@modelcontextprotocol/sdk/types.js";
import { z } from "zod";
import type { ExtApiClient } from "./ext-api-client.js";
import { toolJson } from "./result-format.js";
const text=z.string().min(1);const scope={teamid:text,adbid:text,runId:text};
const base={adoid:text,expectedRevision:text};
const schemas={
 anydb_agent_create_record:z.object({...scope,operationId:text,input:z.object({...base,templateId:text,name:text,values:z.record(z.union([z.string(),z.number().finite(),z.boolean(),z.null()])),reuseExisting:z.literal(true)}).strict()}).strict(),
 anydb_agent_read_record:z.object({...scope,adoid:text}).strict(),
 anydb_agent_update_fields:z.object({...scope,operationId:text,input:z.object({...base,values:z.record(z.union([z.string(),z.number().finite(),z.boolean(),z.null()]))}).strict()}).strict(),
 anydb_agent_set_cell_lock:z.object({...scope,operationId:text,input:z.object({...base,field:text,locked:z.boolean()}).strict()}).strict(),
 // ISSUE - 501: a summary email needs no record; adoid and expectedRevision come together or not at all.
 anydb_agent_send_email:z.object({...scope,operationId:text,input:z.object({adoid:text.optional(),expectedRevision:text.optional(),to:z.array(z.string().email()).min(1).max(25),subject:text,body:text}).strict().refine(value=>!!value.adoid===!!value.expectedRevision,"adoid and expectedRevision must be given together")}).strict(),
 anydb_agent_email_report:z.object({...scope,operationId:text,input:z.object({reportId:text,format:z.enum(["csv","xlsx"]),refresh:z.boolean().optional(),to:z.array(z.string().email()).min(1).max(25),note:z.string().max(2000).optional()}).strict()}).strict(),
 anydb_agent_email_document:z.object({...scope,operationId:text,input:z.object({...base,docgenId:text,asPdf:z.boolean().optional(),to:z.array(z.string().email()).min(1).max(25),note:z.string().max(2000).optional()}).strict()}).strict(),
};
const string={type:"string",minLength:1};const scopeProperties={teamid:string,adbid:string,runId:{...string,description:"Run ID supplied by the trusted workflow runtime"}};
const snapshotSchema = { type: "object", properties: { name: {type:"string"}, templateName: {type:"string"}, revision: string, values: { type: "object", additionalProperties: true }, locks: { type: "object", additionalProperties: { type: "boolean" } }, fieldLabels: {type:"object",additionalProperties:{type:"string"}} }, required: ["name", "templateName", "revision", "values", "locks"], additionalProperties: false };
const outcomeSchema: NonNullable<Tool["outputSchema"]> = { type: "object", properties: {
 state: { type: "string", enum: ["simulated", "applied", "sent", "reused", "failed", "unknown"] }, before: snapshotSchema,
 after: { anyOf: [snapshotSchema, { type: "null" }] },
 receipt: { type: "object", properties: { operationId: string, correlationId: string, messageId: { type: "string" },childRecordId:{type:"string"},reusedExisting:{type:"boolean"},recipients:{type:"array",items:{type:"string"}},attachment:{type:"object",properties:{filename:{type:"string"},bytes:{type:"number"}},required:["filename","bytes"],additionalProperties:false},note:{type:"string"} }, required: ["operationId", "correlationId"], additionalProperties: false },
 error: { type: "string" }
}, required: ["state", "before", "after", "receipt"], additionalProperties: false };
const limitations="Requires an authenticated run capability carried outside tool arguments. Saved field positions, record IDs and email recipients further restrict current caller ACLs. Server chooses preview/live mode; never supply identity or simulate overrides. Preview supports literal number/boolean/text/user-ID values and locks only, with overlay-aware reads; no formula, script or downstream workflow effects. Agent writes suppress workflow events. A receipt state is simulated, applied, sent, failed or unknown. Unknown acceptance must never be retried under a new operation ID; replay the original ID and identical arguments.";
/** record "required" (default): input names a record and its revision; "none": no record; "optional": both or neither. */
function operation(name:keyof typeof schemas,description:string,properties:Record<string,unknown>,required:string[],record:"required"|"none"|"optional"="required"):Tool {
 const recordProperties=record==="none" ? {} : {adoid:string,expectedRevision:{...string,description:"Revision from latest anydb_agent_read_record"}};
 const recordRequired=record==="required" ? ["adoid","expectedRevision"] : [];
 return {name,outputSchema:outcomeSchema,description:`${description} ${limitations}`,inputSchema:{type:"object",additionalProperties:false,properties:{...scopeProperties,operationId:string,input:{type:"object",additionalProperties:false,properties:{...recordProperties,...properties},required:[...recordRequired,...required]}},required:["teamid","adbid","runId","operationId","input"]}};
}
export const AGENT_TOOLS:Tool[]=[
 {name:"anydb_agent_read_record",outputSchema:{...snapshotSchema,type:"object"},description:`Read the current owning-authorized record name and type (templateName), visible scoped field values, locks and revision, including this preview's simulated changes. ${limitations}`,inputSchema:{type:"object",additionalProperties:false,properties:{...scopeProperties,adoid:string},required:["teamid","adbid","runId","adoid"]}},
 operation("anydb_agent_update_fields","Update existing allowed fields with literal values; user references use an actual current team user ID.",{values:{type:"object",additionalProperties:{type:["string","number","boolean","null"]}}},["values"]),
 operation("anydb_agent_set_cell_lock","Set one allowed cell's lock flag. Already locked fields cannot be changed or unlocked by this pilot.",{field:string,locked:{type:"boolean"}},["field","locked"]),
 operation("anydb_agent_send_email","Send one plain-text email to the agent's saved recipients with a correlated single-attempt receipt. Use it to send a summary or report you wrote yourself from data you read; it needs no record (omit adoid and expectedRevision; give both only to tie the email to a record that is in scope). Write the body as light markdown: it is rendered as a formatted business email by a fixed template, with the subject as its title. Supported: # ## ### headings, **bold**, *italic*, `code`, [text](https://url) links (absolute http or https only), - and 1. lists, pipe tables with a |---| separator row, and --- rules. Raw HTML is never rendered (it appears as literal text), there are no images, colours or attachments, and the body is at most 20000 characters. The original text is also sent as the plain-text part. Recipients must be saved on the agent; counts against the team's daily email limit in live mode. Sent means SMTP accepted; it is not inbox delivery confirmation.",{to:{type:"array",minItems:1,maxItems:25,items:{type:"string",format:"email"}},subject:string,body:string},["to","subject","body"],"optional"),
 operation("anydb_agent_create_record","Create a typed child under a saved parent/type/initial-field rule; reuse one existing authorized child, and refuse multiple matches. Reuse does not overwrite existing values. receipt.childRecordId identifies the child for final anydb_agent_read_record; preview returns a virtual child without business writes. Unknown acceptance is fenced across runs.",{templateId:string,name:string,values:{type:"object",additionalProperties:{type:["string","number","boolean","null"]}},reuseExisting:{type:"boolean",const:true}},["templateId","name","values","reuseExisting"]),
 operation("anydb_agent_email_report","Email the export (csv or xlsx) of a saved-scope report to saved recipients. You cannot attach anything else or write the message: the only content is the report export the server produces, plus an optional short plain-text note. Needs no record, so a scheduled agent can use it. refresh:true runs the report and waits for the new snapshot first; if it does not finish, the call fails and nothing is sent, so never describe stale numbers as fresh. Without refresh it emails the latest ready snapshot. In test mode it checks and produces the file and returns state simulated with the attachment name and size; the report is NOT run and nothing is sent. Exports over 5 MB fail with the reason. Counts against the team's daily email limit in live mode.",{reportId:string,format:{type:"string",enum:["csv","xlsx"]},refresh:{type:"boolean"},to:{type:"array",minItems:1,maxItems:25,items:{type:"string",format:"email"}},note:{type:"string",maxLength:2000}},["reportId","format","to"],"none"),
 operation("anydb_agent_email_document","Render a saved-scope document template for a record and email the result to saved recipients. You cannot attach anything else or write the message. The record must be in scope and expectedRevision must be the revision you just read. The document is rendered fresh and no record is created or changed. In test mode it renders and checks, returns state simulated with the attachment name and size, and sends nothing. Counts against the team's daily email limit in live mode.",{docgenId:string,asPdf:{type:"boolean"},to:{type:"array",minItems:1,maxItems:25,items:{type:"string",format:"email"}},note:{type:"string",maxLength:2000}},["docgenId","to"])
];
export const isAgentTool=(name:string):name is keyof typeof schemas=>Object.prototype.hasOwnProperty.call(schemas,name);
export async function callAgentTool(name:string,args:unknown,client:ExtApiClient) {
 if(!isAgentTool(name)) throw new Error("Unknown agent operation");
 const input=schemas[name].parse(args);
 const result=name==="anydb_agent_read_record"?await client.readAgentRecord(input):await client.executeAgentOperation({...input,kind:name.slice("anydb_agent_".length)});
 if (!result || typeof result !== "object" || Array.isArray(result)) throw new Error("Invalid agent operation response");
 return {structuredContent: result as Record<string, unknown>, content:[{type:"text" as const,text:toolJson(result,client.getOriginClient())}]};
}
